lecture3/birthday/urls.py
from django.urls import path
from . import views
urlpatterns = [

    path("", views.index, name="index")
]

lecture3/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("olamide", views.olamide, name="olamide")
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('birthday/', include("birthday.urls")),
    path('tasks/', include("tasks.urls"))
]

lecture3/newyear/urls.py
from django.urls import path
from . import views
urlpatterns = [

    path("", views.index, name="index")
]

lecture3/tasks/urls.py
from django.urls import path
from . import views

#name to uniquely identify the URLs in tasks.
app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
    
]

lecture3/birthday/models.py
from django.db import models

# Create your models here.

lecture3/hello/models.py
from django.db import models

# Create your models here.

lecture3/newyear/models.py
from django.db import models

# Create your models here.

lecture3/tasks/models.py
from django.db import models

# Create your models here.

lecture3/birthday/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "birthday/index.html", {
        "birthday": now.month==1 and now.day == 4
        #"birthday": now.month==25 and now.day == 3
    }) 

lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    #return HttpResponse("Hello, world!")
    return render(request, "hello/index.html")

def olamide(request):
    return HttpResponse("Hello, Olamide!")

def greet(request, name):
    #return HttpResponse(f'Hello {name.capitalize()}!')
    return render(request, "hello/greet.html", {
        "name":name.capitalize()
    })

lecture3/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month==1 and now.day == 1
    })

lecture3/tasks/views.py
from django import forms
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

#tasks = []

#Creating form to add new tasks.
#defining the class

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        #"tasks":tasks
        "tasks": request.session["tasks"]
    })

def add(request):
    #getting all the data submitted by the user.
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        #checks if the form has no errors
        if form.is_valid():
            task = form.cleaned_data["task"]
            #tasks.append(task)
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                #return the existing data form to the user
                "form": form
            })
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

lecture3/birthday/templates/birthday/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Olamide Ilori's birthday!</title>
        <style>
            body{
                background-color: black;
            }
            h1{
                text-align: center;
                font-family: Georgia, 'Times New Roman', Times, serif;
                font-size: 50px;
                font-weight: bold;
                color: darkorange;
            }
        </style>
    </head>
    <body>
        {% if birthday %}
            <h1>Happy birthday, Olamide!</h1>
            <img src="olamide-ilori.jpeg" alt="Olamide Ilori's picture">
        {% else %}
            <h1>Today is not Olamide's birthday.</h1>
        {% endif %}
    </body>
</html>

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
        <style>
            body{
                background-color: chocolate;
            }
        </style>
    </head>
    <body>
        <h1>Hello, {{name}}!</h1>
    </body>
</html>

lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
        <style>
            body{
                background-color: chocolate;
            }
        </style>
    </head>
    <body>
        <h1>Hello, world!</h1>
    </body>
</html>

lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it a New Year?</title>
        <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

lecture3/tasks/templates/tasks/add.html
<!--Template inheritance in Django-->
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>Add new tasks here.</h1>
        <form action="{% url 'tasks:add' %}" method="post">
            {% csrf_token %}
            <!--plug in Django form here-->
            {{ form }}
            <input type="submit">
        </form>
        <a href="{% url 'tasks:index' %}">Click here to view tasks.</a>
{% endblock %}

lecture3/tasks/templates/tasks/index.html
<!--Template inheritance in Django-->
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>My Tasks:</h1>
        <ul>
            {% for task in tasks %}
                <li>{{ task }}</li>
            {% empty %}
                <li>You currently have zero task.</li>
            {% endfor %}
        </ul>
        <a href="{% url 'tasks:add' %}">Click here to add new tasks.</a>
{% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>My Task List</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>